import { NextResponse } from 'next/server';

const transferRumors = [
  {
    id: 1,
    player: "Florian Wirtz",
    position: "Attacking Midfielder",
    currentClub: "Bayer Leverkusen",
    currentLeague: "Bundesliga",
    targetClub: "Real Madrid",
    targetLeague: "La Liga",
    fee: 150000000,
    feeDisplay: "€150M",
    status: "Negotiating" as const,
    confidence: 78,
    source: "Marca",
    date: "2025-07-10",
    nationality: "Germany",
    age: 22,
  },
  {
    id: 2,
    player: "Jamal Musiala",
    position: "Central Midfielder",
    currentClub: "Bayern Munich",
    currentLeague: "Bundesliga",
    targetClub: "Manchester City",
    targetLeague: "Premier League",
    fee: 130000000,
    feeDisplay: "€130M",
    status: "Agreed" as const,
    confidence: 92,
    source: "Sky Sports",
    date: "2025-07-08",
    nationality: "Germany",
    age: 22,
  },
  {
    id: 3,
    player: "Lamine Yamal",
    position: "Right Winger",
    currentClub: "FC Barcelona",
    currentLeague: "La Liga",
    targetClub: "Paris Saint-Germain",
    targetLeague: "Ligue 1",
    fee: 250000000,
    feeDisplay: "€250M (Release Clause)",
    status: "Rumor" as const,
    confidence: 25,
    source: "Sport",
    date: "2025-07-12",
    nationality: "Spain",
    age: 18,
  },
  {
    id: 4,
    player: "Declan Rice",
    position: "Defensive Midfielder",
    currentClub: "Arsenal",
    currentLeague: "Premier League",
    targetClub: "Real Madrid",
    targetLeague: "La Liga",
    fee: 120000000,
    feeDisplay: "€120M",
    status: "Medical" as const,
    confidence: 85,
    source: "The Athletic",
    date: "2025-07-09",
    nationality: "England",
    age: 26,
  },
  {
    id: 5,
    player: "William Saliba",
    position: "Centre-Back",
    currentClub: "Arsenal",
    currentLeague: "Premier League",
    targetClub: "Real Madrid",
    targetLeague: "La Liga",
    fee: 100000000,
    feeDisplay: "€100M",
    status: "Rumor" as const,
    confidence: 35,
    source: "Fabrizio Romano",
    date: "2025-07-11",
    nationality: "France",
    age: 24,
  },
  {
    id: 6,
    player: "Martin Ødegaard",
    position: "Attacking Midfielder",
    currentClub: "Arsenal",
    currentLeague: "Premier League",
    targetClub: "FC Barcelona",
    targetLeague: "La Liga",
    fee: 90000000,
    feeDisplay: "€90M",
    status: "Negotiating" as const,
    confidence: 55,
    source: "Mundo Deportivo",
    date: "2025-07-07",
    nationality: "Norway",
    age: 26,
  },
  {
    id: 7,
    player: "Cole Palmer",
    position: "Right Winger",
    currentClub: "Chelsea",
    currentLeague: "Premier League",
    targetClub: "Liverpool",
    targetLeague: "Premier League",
    fee: 110000000,
    feeDisplay: "€110M",
    status: "Agreed" as const,
    confidence: 88,
    source: "BBC Sport",
    date: "2025-07-06",
    nationality: "England",
    age: 23,
  },
  {
    id: 8,
    player: "Pedri",
    position: "Central Midfielder",
    currentClub: "FC Barcelona",
    currentLeague: "La Liga",
    targetClub: "Bayern Munich",
    targetLeague: "Bundesliga",
    fee: 100000000,
    feeDisplay: "€100M",
    status: "Rumor" as const,
    confidence: 30,
    source: "Kicker",
    date: "2025-07-13",
    nationality: "Spain",
    age: 22,
  },
  {
    id: 9,
    player: "Rafael Leão",
    position: "Left Winger",
    currentClub: "AC Milan",
    currentLeague: "Serie A",
    targetClub: "Manchester United",
    targetLeague: "Premier League",
    fee: 85000000,
    feeDisplay: "€85M",
    status: "Negotiating" as const,
    confidence: 62,
    source: "Gazzetta dello Sport",
    date: "2025-07-05",
    nationality: "Portugal",
    age: 26,
  },
  {
    id: 10,
    player: "Bukayo Saka",
    position: "Right Winger",
    currentClub: "Arsenal",
    currentLeague: "Premier League",
    targetClub: "Bayern Munich",
    targetLeague: "Bundesliga",
    fee: 140000000,
    feeDisplay: "€140M",
    status: "Medical" as const,
    confidence: 80,
    source: "Sky Germany",
    date: "2025-07-14",
    nationality: "England",
    age: 23,
  },
];

const topValuedPlayers = [
  { rank: 1, name: "Kylian Mbappé", position: "Forward", club: "Real Madrid", marketValue: 200, age: 26, nationality: "France", trend: "up", trendValue: "+10M", initials: "KM", gradient: "from-amber-500 to-orange-600" },
  { rank: 2, name: "Erling Haaland", position: "Striker", club: "Manchester City", marketValue: 190, age: 24, nationality: "Norway", trend: "up", trendValue: "+5M", initials: "EH", gradient: "from-sky-500 to-cyan-600" },
  { rank: 3, name: "Lamine Yamal", position: "Right Winger", club: "FC Barcelona", marketValue: 180, age: 18, nationality: "Spain", trend: "up", trendValue: "+30M", initials: "LY", gradient: "from-rose-500 to-pink-600" },
  { rank: 4, name: "Florian Wirtz", position: "Attacking Midfielder", club: "Bayer Leverkusen", marketValue: 150, age: 22, nationality: "Germany", trend: "up", trendValue: "+20M", initials: "FW", gradient: "from-red-500 to-rose-600" },
  { rank: 5, name: "Jude Bellingham", position: "Central Midfielder", club: "Real Madrid", marketValue: 150, age: 22, nationality: "England", trend: "stable", trendValue: "0", initials: "JB", gradient: "from-violet-500 to-purple-600" },
  { rank: 6, name: "Bukayo Saka", position: "Right Winger", club: "Arsenal", marketValue: 140, age: 23, nationality: "England", trend: "up", trendValue: "+15M", initials: "BS", gradient: "from-emerald-500 to-teal-600" },
  { rank: 7, name: "Rodri", position: "Defensive Midfielder", club: "Manchester City", marketValue: 130, age: 28, nationality: "Spain", trend: "down", trendValue: "-5M", initials: "RH", gradient: "from-blue-500 to-indigo-600" },
  { rank: 8, name: "Jamal Musiala", position: "Central Midfielder", club: "Bayern Munich", marketValue: 130, age: 22, nationality: "Germany", trend: "up", trendValue: "+10M", initials: "JM", gradient: "from-red-600 to-amber-600" },
  { rank: 9, name: "Vinícius Júnior", position: "Left Winger", club: "Real Madrid", marketValue: 200, age: 24, nationality: "Brazil", trend: "stable", trendValue: "0", initials: "VJ", gradient: "from-amber-400 to-yellow-500" },
  { rank: 10, name: "Declan Rice", position: "Defensive Midfielder", club: "Arsenal", marketValue: 120, age: 26, nationality: "England", trend: "up", trendValue: "+5M", initials: "DR", gradient: "from-teal-500 to-cyan-600" },
];

const completedTransfers = [
  { id: 1, player: "Leny Yoro", position: "Centre-Back", fromClub: "LOSC Lille", toClub: "Real Madrid", fee: 70000000, feeDisplay: "€70M", date: "2025-07-01", nationality: "France", age: 19, initials: "LY", gradient: "from-slate-500 to-zinc-600" },
  { id: 2, player: "Xavi Simons", position: "Attacking Midfielder", fromClub: "RB Leipzig", toClub: "FC Barcelona", fee: 80000000, feeDisplay: "€80M", date: "2025-06-28", nationality: "Netherlands", age: 22, initials: "XS", gradient: "from-red-500 to-rose-600" },
  { id: 3, player: "Alphonso Davies", position: "Left-Back", fromClub: "Bayern Munich", toClub: "Real Madrid", fee: 50000000, feeDisplay: "€50M", date: "2025-06-25", nationality: "Canada", age: 24, initials: "AD", gradient: "from-rose-500 to-red-600" },
  { id: 4, player: "Marcus Rashford", position: "Left Winger", fromClub: "Manchester United", toClub: "AC Milan", fee: 45000000, feeDisplay: "€45M (Loan + Obligation)", date: "2025-07-03", nationality: "England", age: 27, initials: "MR", gradient: "from-red-600 to-black" },
  { id: 5, player: "Victor Osimhen", position: "Striker", fromClub: "Galatasaray", toClub: "Chelsea", fee: 75000000, feeDisplay: "€75M", date: "2025-06-30", nationality: "Nigeria", age: 26, initials: "VO", gradient: "from-blue-600 to-sky-600" },
  { id: 6, player: "Jeremie Frimpong", position: "Right-Back", fromClub: "Bayer Leverkusen", toClub: "Liverpool", fee: 40000000, feeDisplay: "€40M", date: "2025-07-02", nationality: "Netherlands", age: 24, initials: "JF", gradient: "from-red-600 to-amber-500" },
  { id: 7, player: "Alejandro Grimaldo", position: "Left-Back", fromClub: "Bayer Leverkusen", toClub: "Manchester City", fee: 35000000, feeDisplay: "€35M", date: "2025-07-05", nationality: "Spain", age: 29, initials: "AG", gradient: "from-emerald-500 to-teal-600" },
  { id: 8, player: "Nico Williams", position: "Left Winger", fromClub: "Athletic Bilbao", toClub: "FC Barcelona", fee: 62000000, feeDisplay: "€62M", date: "2025-07-04", nationality: "Spain", age: 22, initials: "NW", gradient: "from-red-500 to-white" },
];

const clubActivity = [
  { club: "Real Madrid", league: "La Liga", ins: 4, outs: 2, spending: 220, income: 40, net: 180, color: "bg-amber-500" },
  { club: "FC Barcelona", league: "La Liga", ins: 3, outs: 1, spending: 142, income: 0, net: 142, color: "bg-rose-500" },
  { club: "Manchester City", league: "Premier League", ins: 3, outs: 2, spending: 105, income: 25, net: 80, color: "from-sky-500 to-cyan-500" },
  { club: "Chelsea", league: "Premier League", ins: 2, outs: 3, spending: 75, income: 55, net: 20, color: "bg-blue-600" },
  { club: "Arsenal", league: "Premier League", ins: 2, outs: 3, spending: 60, income: 220, net: -160, color: "bg-red-600" },
];

export async function GET() {
  return NextResponse.json({
    rumors: transferRumors,
    topValued: topValuedPlayers,
    completed: completedTransfers,
    clubActivity,
    summary: {
      totalRumors: transferRumors.length,
      totalCompleted: completedTransfers.length,
      totalSpending: clubActivity.reduce((acc, c) => acc + c.spending, 0),
      mostActiveClub: "Real Madrid",
      highestFee: "€250M (Yamal Release Clause)",
    },
  });
}
